name: Build

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Maven
      uses: stCarolas/setup-maven@v4.1
    
    - name: Install JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Publish artifact
      uses: actions/upload-artifact@v2
      with:
        name: plugin-template
        path: target/*.jar
